### ISSUE TITLE
Intermediate Task: Document all library dependencies 

### ISSUE THREAD

**Issue by KarlosMuradyan** [UBC-MDS/DMC_Portuguese_Group_402#4]
As we are about to start our project and as at the end we should integrate it in docker, it is very important to keep track what libraries we are using. I would like to ask you to document all libraries that you use in this issue, so that we won't spend time for figuring the list at the end of the project.

**Comment by KarlosMuradyan** [comment]
- os
- requests
- zipfile
- itertools
- argparse

**Comment by fsywang** [comment]
- pandas
- altair
- seaborn
- sklearn
- selenium = '3.141.0'

systerm requirement: 
- chromedriver: $ brew cask install chromedriver

**Comment by KarlosMuradyan** [comment]
all requirements are documented in `requirements.txt` file
