### ISSUE TITLE
Milestone 3 Feedback: Accuracy

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DMC_Portuguese_Group_402#57]
This is what I get when I run `make all`:

```
python src/preprocessing.py --input_file=data/raw/bank.csv --out_train_file=data/clean/bank_train.csv --out_test_file=data/clean/bank_test.csv
Successfully created the file  testing/test.csv
Traceback (most recent call last):
  File "src/preprocessing.py", line 184, in <module>
    main(opt['--input_file'],opt['--out_train_file'],opt['--out_test_file'],opt['--test_split_size'],opt['--unproc_train_req'])
  File "src/preprocessing.py", line 61, in main
    ('ohe', OneHotEncoder(drop='first'), categorical_features)])
TypeError: __init__() got an unexpected keyword argument 'drop'
make: *** [data/clean/bank_train.csv] Error 1
```

**Comment by KarlosMuradyan** [comment]
@Nazliozum could you please check if your scikit-learn version matches the one mentioned in `requirements.txt` file?

I think from scikit-learn 0.20, the function changed and `drop` argument has been added to it.

**Comment by Nazliozum** [comment]
@KarlosMuradyan thank you for the clarification, it was indeed because of the dependencies! I am closing this issue then. Side note, I recognized there is some repetition in your requirements.txt file, so you might want to eliminate that.
